//ACTION TYPES

//ADD ITEM
export const ADDING_ITEM = "ADDING_ITEM";
export const ADD_ITEM = "ADD_ITEM";
export const ADDING_ITEM_ERROR = "ADDING_ITEM_ERROR";

//REMOVE ITEM
export const REMOVING_ITEM = "REMOVING_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const REMOVING_ITEM_ERROR = "REMOVING_ITEM_ERROR";

//GET ITEMS
export const GETTING_ITEMS = "GETTING_ITEMS";
export const GET_ITEMS = "GET_ITEMS";
export const GETTING_ITEMS_ERROR = "GETTING_ITEMS_ERROR";

//EDIT ITEM
export const EDITING_ITEM = "EDITING_ITEM";
export const EDIT_ITEM = "EDIT_ITEM";
export const EDITING_ITEM_ERROR = "EDITING_ITEM_ERROR";

//COMPLETED ITEM
export const COMPLETING_ITEM = "COMPLETING_ITEM";
export const COMPLETED_ITEM = "COMPLETED_ITEM";
export const COMPLETING_ITEM_ERROR = "COMPLETING_ITEM_ERROR";